import gradio as gr
import openai
import PyPDF2


def summarize_pdf(pdf):
  # Open the PDF file
  pdf_file = open(pdf.name, 'rb')

  # Create a PDF reader object
  pdf_reader = PyPDF2.PdfFileReader(pdf_file)

  # Get the number of pages in the PDF file
  num_pages = pdf_reader.getNumPages()

  # Extract text from each page of the PDF file
  text = ''
  for i in range(num_pages):
    page = pdf_reader.getPage(i)
    text += page.extractText()

  # Close the PDF file
  pdf_file.close()

  # Set up the OpenAI API credentials
  openai.api_key = 'YOUR_API_KEY'

  # Set up the prompt for GPT-3
  prompt = 'Please summarize the following text: ' + text

  # Set up the parameters for GPT-3
  parameters = {
    'model': 'text-davinci-002',
    'prompt': prompt,
    'temperature': 0.7,
    'max_tokens': 60,
    'stop': '\n'
  }

  # Call the GPT-3 API to generate a summary
  response = openai.Completion.create(**parameters)

  # Return the summary generated by GPT-3
  return response.choices[0].text.strip()


iface = gr.Interface(
  fn=summarize_pdf,
  inputs="file",
  outputs="text",
  title="PDF Summarizer",
  description="Upload a PDF document and this tool will generate a summary of its contents using GPT-3."
)
iface.launch(share=True)
